Updated readme.md

diff --git a/app/libs/justfile b/app/libs/justfile
--- a/app/libs/justfile
+++ b/app/libs/justfile
@@ -17,6 +17,7 @@ export CI          := env_var_or_default("CI", "")
 export JEKYLL_ENV  := env_var_or_default("JEKYLL_ENV", "production")
 parcel             := "./node_modules/parcel-bundler/bin/cli.js"
 tsc                := "./node_modules/typescript/bin/tsc"
+vite               := "NODE_OPTIONS='--max_old_space_size=16384' ./node_modules/vite/bin/vite.js"
 # minimal formatting, bold is very useful
 bold               := '\033[1m'
 normal             := '\033[0m'
@@ -30,33 +31,38 @@ _build: _ensure_node_modules _build_npm
     #!/usr/bin/env bash
     set -euo pipefail
 
-    echo -e "🍳👉 {{bold}}Building standalone browser downloads{{normal}}"
-    just _build_browser_modules {{NPM_MODULE_OUTPUT}}/browser/
+    # echo -e "🍳👉 {{bold}}Building standalone browser downloads{{normal}}"
+    # just _build_browser_modules {{NPM_MODULE_OUTPUT}}/browser/
 
-    # copy production builds to the (dev+docs+test) dir
-    for MODULES_TARGET in "test/page/js"; do
-        mkdir -p $MODULES_TARGET
-        for meta in "metapage" "metaframe"; do
-            rm -rf $MODULES_TARGET/$meta
-            cp -r {{NPM_MODULE_OUTPUT}}/browser/$meta $MODULES_TARGET/
-        done
-    done
-    echo "✅ {{NPM_MODULE_OUTPUT}}/browser/metapage"
-    echo "✅ {{NPM_MODULE_OUTPUT}}/browser/metaframe"
-    echo "✅ test/page/js/"
+    # # copy production builds to the (dev+docs+test) dir
+    # for MODULES_TARGET in "test/page/js"; do
+    #     mkdir -p $MODULES_TARGET
+    #     for meta in "metapage" "metaframe"; do
+    #         rm -rf $MODULES_TARGET/$meta
+    #         cp -r {{NPM_MODULE_OUTPUT}}/browser/$meta $MODULES_TARGET/
+    #     done
+    # done
+    # echo "✅ {{NPM_MODULE_OUTPUT}}/browser/metapage"
+    # echo "✅ {{NPM_MODULE_OUTPUT}}/browser/metaframe"
+    # echo "✅ test/page/js/"
 
 _build_npm:
     #!/usr/bin/env bash
     set -euo pipefail
     # Compiles the entire codebase to typescript files in ./dist. Packaged into the npm module '{{NPM_MODULE}}'
     # How to test installation of the build?
-    mkdir -p {{NPM_MODULE_OUTPUT}}
-    echo -e "🍳👉 {{bold}}Compiling typescript  => {{NPM_MODULE_OUTPUT}}/{{normal}}"
-    {{tsc}} --outDir {{NPM_MODULE_OUTPUT}}
-    # cp package.json      {{NPM_MODULE_OUTPUT}}/package.json
-    # cp README-PACKAGE.md {{NPM_MODULE_OUTPUT}}/README.md
-    # cp LICENSE           {{NPM_MODULE_OUTPUT}}/
-    echo "✅ {{NPM_MODULE_OUTPUT}}"
+    {{tsc}} --noEmit
+    echo "✅ typescript check"
+    {{vite}} build
+    echo "✅ vite build"
+
+    # mkdir -p {{NPM_MODULE_OUTPUT}}
+    # echo -e "🍳👉 {{bold}}Compiling typescript  => {{NPM_MODULE_OUTPUT}}/{{normal}}"
+    # {{tsc}} --outDir {{NPM_MODULE_OUTPUT}}
+    # # cp package.json      {{NPM_MODULE_OUTPUT}}/package.json
+    # # cp README-PACKAGE.md {{NPM_MODULE_OUTPUT}}/README.md
+    # # cp LICENSE           {{NPM_MODULE_OUTPUT}}/
+    # echo "✅ {{NPM_MODULE_OUTPUT}}"
 
 _tsc +args="":
     {{tsc}} {{args}}
@@ -124,15 +130,15 @@ _versions-write-versions-to-jekyll:
 publish: _require_NPM_TOKEN _ensure_node_modules
     #!/usr/bin/env bash
     set -euo pipefail
-    if [ "$CI" != "true" ]; then
-        # This check is here to prevent publishing if there are uncommitted changes, but this check does not work in CI environments
-        # because it starts as a clean checkout and git is not installed and it is not a full checkout, just the tip
-        if [[ $(git status --short) != '' ]]; then
-            git status
-            echo -e '💥 Cannot publish with uncommitted changes'
-            exit 2
-        fi
-    fi
+    # if [ "$CI" != "true" ]; then
+    #     # This check is here to prevent publishing if there are uncommitted changes, but this check does not work in CI environments
+    #     # because it starts as a clean checkout and git is not installed and it is not a full checkout, just the tip
+    #     if [[ $(git status --short) != '' ]]; then
+    #         git status
+    #         echo -e '💥 Cannot publish with uncommitted changes'
+    #         exit 2
+    #     fi
+    # fi
     VERSION=`cat package.json | jq -r '.version'`
     INDEX=`npm view {{NPM_MODULE}} versions --json | jq "index( \"$VERSION\" )"`
     if [ "$INDEX" != "null" ]; then
@@ -164,7 +170,17 @@ clean:
     just test/clean
 
 # build meta(page/frame) browser modules for testing
-_build_browser_modules outdir testing="":
+_build_browser_modules:
+    #!/usr/bin/env bash
+    set -euo pipefail
+    # Should not need to do this because earlier steps compile check
+    {{tsc}} --noEmit
+    echo "✅ typescript check"
+    {{vite}} build
+    echo "✅ vite build"
+
+
+_build_browser_modules-OLD outdir testing="":
     #!/usr/bin/env bash
     set -euo pipefail
     rm -rf {{outdir}}/metaframe
